import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*
  #5.16 Layout part One
  모바일 웹 사이트에 최대 너비 설정하여 좌우 여백을 줌

  Max-Width
  요소의 최대 너비를 설정

  max-w-none => max-width: none;
  max-w-xs => max-width: 20rem; ( 320px )
  max-w-sm => max-width: 24rem; ( 384px )
  max-w-md => max-width: 28rem; ( 448px )
  max-w-lg => max-width: 32rem; ( 512px )
  max-w-full => max-width: 100%;
  max-w-screen-sm => max-width: 640px;
  max-w-screen-md => max-width: 768px;
  max-w-screen-lg => max-width: 1024px;
  max-w-screen-xl => max-width: 1280px;
  ...

  대괄호를 사용하여 임의의 값을 사용하여 즉시 속성을 생성 가능
  div class="max-w-[50%]"
 */

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full max-w-lg mx-auto">{children}</div>
      </body>
    </html>
  );
}
